### ISSUE TITLE
Update to build on recent intel-drm-next

### ISSUE THREAD

**Issue by pl-semiotics** [ipts-linux-org/ipts-linux#1]
This patch set requires several changes to the i915 driver, which has changed a lot in recent DRM trees, making the patch set fail to apply cleanly.  Most devices shipping with Precise Touch also use Skylake processors, and skylake graphics stability has also improved drastically with these changes, making the ability to use more recent kernels very desirable.

I am working on trying to forward-port the i915 changes, although I haven't worked on the driver before and so may make some egregious mistakes.

**Comment by pl-semiotics** [comment]
A number of very small changes related to name changes and substitutions of `drm_i915_private` for `drm_device` are required, which I have had some luck with.

The first major issue that I've noticed is that `vmapping_count` and `dma_buf_vmapping` have been removed from `drm_i915_private` (commit 0a798eb92e6dcc1cba45d13d7b75a523e5d0fc4c "drm/i915: Refactor duplicate object vmap functions").  This patch seems to remove the `vmapping_count` used for the lifetime of the `dma_buf_vmapping` and instead decide when to map/unmap the new single `mapping` based on the lifetime of `obj->pages`.

`itouch_object_map` and `itouch_object_unmap` do not use `i915_gem_get_pages` and `i915_gem_object_pin_pages`/`i915_gem_object_unpin_pages`, so it looks to me like the lifetime of this mapping shouldn't be coupled to the lifetime of the pages from the main driver.  If this is true, I am unsure what the correct fix is here.

**Comment by ardacoskunses** [comment]
Hi Peter,

Yes I noticed the issue when I am porting to 4.7 kernel due to the exact changes you mentioned.
I am working on adapting to the new changes.

I will update here with my progress.

**Comment by pl-semiotics** [comment]
Hi Arda,

Great, thank you! Also, in case it is at all helpful, I tried building a kernel with `vmapping_count` and `dma_buf_vmapping` added back in, but without changing any of the other former consumers back to using them; this resulted in a clean build, but the touch driver didn't work properly on subsequent boot.  I believe that this may be related to the fact that this patchset is somehow triggering the `WARN_ON(desc.engines_used == 0);` from `guc_init_ctx_desc`

Please let me know if there is anything else that I could do that would be helpful!

**Comment by ardacoskunses** [comment]
This kernel in this repo only uses GuC version 4.3. As you are working on 4.7 kernel I assume you are using GuC 6.1. Did you install GuC version 6.1 from https://01.org/linuxgraphics/intel-linux-graphics-firmwares ? After enabling GuC submission you can check with: cat /sys/kernel/debug/dri/0/i915_guc_info

If numbers stuck at 0 GuC is not active, if they are changing it should be OK. Then in intel_touch.c a change is required to select the right engine (3D engine for our case).

**Comment by pl-semiotics** [comment]
My /lib/firmware/i915 includes the 4.3 GuC from this repository and also a version 6.1 GuC, which I believe comes from linux-firmware 20160516, and is identical to the one from that link; is this the correct GuC, or does it need some different changes?

The GuC does appear to be active, as the render ring count (and GuC total submission count) is changing (and the total action count is high, although it is static/changing much more slowly).  I am also rebuilding a kernel with drm debugging & itouch debugging.

What should I change in intel_touch.c?

**Comment by ardacoskunses** [comment]
OK your GuC is active indeed. When itouch init debug should print the GTT addresses, are they valid or NULL? 

The part I refer to
page = i915_gem_object_get_page(ctx->engine[0].state, LRC_STATE_PN);
reg_state = kmap_atomic(page);
But it seems like you have right changes already.

It would be useful to take a look at your kernel logs.

**Comment by pl-semiotics** [comment]
For some reason, my machine won't boot with itouch and drm debug active.  Unfortunately, I have run out of time tonight, but I will look into it more, and try to get logs, tomorrow morning.  Thanks for looking into this!

**Comment by ardacoskunses** [comment]
Yea I understand, here is a temporary trick until we solve the issue:
in /drivers/misc/itouch/mei-itouch-client.c

static struct mei_cl_device_id itouch_mei_cl_tbl[] = {
-   {"", MEI_ITOUCH_UUID,MEI_CL_VERSION_ANY},
-      {"**name**", MEI_ITOUCH_UUID,MEI_CL_VERSION_ANY},
  {}
  };

This way IPTS wont start during boot, you can start later on with "insmod" ing the module.

I could not spend time on this today, I will update once I have more information. 

Good night!

**Comment by pl-semiotics** [comment]
It looks like the crash with debugs that I am seeing is coming from `i915_print_itouch_guc_info`, and is happening because `ctx->engine[0].state` is null.  This seems like it may be related to the `desc.engines_used == 0` warning that I am seeing from `guc_init_ctx_desc`.  There is also this comment in the loop that sets `desc.engines_used` that seems related:

```
            /* TODO: We have a design issue to be solved here. Only when we
             * receive the first batch, we know which engine is used by the
             * user. But here GuC expects the lrc and ring to be pinned. It
             * is not an issue for default context, which is the only one
             * for now who owns a GuC client. But for future owner of GuC
             * client, need to make sure lrc is pinned prior to enter here.
             */
```

I think that the problem may be that a code path in the i915 driver that used to initialize the engines has changed and no longer does so.

The root problem of course might just be my current hack for getting around the vmapping changes --- is it important that it use the same `vmapping` that is used elsewhere?  If so, is it reasonable for it to use `i915_gem_object_pin_map()`?

I am not sure where the GTT addresses are be in the output (and don't see anything that directly refers to them), even with all of the debugging #defines uncommented.  Do I also need DRM debugging?.

I have the lines that you mentioned above as part of `i915_print_itouch_guc_info`, but nowhere else; is there somewhere else that they should be?

Thanks again, and I do hope that these observations are at least a little helpful.

**Comment by ardacoskunses** [comment]
Hi Peter,

Today I could spend some time on this.
Vmap changes required but based on logs itouch guc client registration is failing. It seems like the context we used to register is not valid anymore as you have noticed engines and rings getting initialized differently. I will change the context init. I did vmap changes but couldn't test as guc registration failing as of now.

**Comment by pl-semiotics** [comment]
Hi Arda,

Great, thanks! Let me know if there is anything else that I can do to help (and I do hope that I've been a bit helpful so far).

**Comment by pl-semiotics** [comment]
Hi Arda,

I believe that the issue that I am seeing here is related to commit 978f1e09abdf46413cba0dc3b1310abc840e3402, which removed the call to `intel_lr_context_deferred_alloc` from `i915_gem_validate_context`, which the itouch driver is using to initialize the context.  I believe that that change did not make it into 4.7, however, so if you are rebasing directly on release 4.7, is there a different issue that you are seeing?

I am using intel-drm-next from 2016-07-19 right now.

**Comment by ardacoskunses** [comment]
Hi Peter,
Thanks for working on this with me, I really appreciate your help!

I was not aware of deferred alloc changes. I am on direct release 4.7.

I managed to make some progress: Itouch context allocation was failing for me (before validate context which calls deferred alloc and vmapping). The function which was failing is:i915_gem_context_create_ioctl

I removed the checks which added on release 4.7 as follows.
--- a/drivers/gpu/drm/i915/i915_gem_context.c
+++ b/drivers/gpu/drm/i915/i915_gem_context.c
@@ -864,22 +864,38 @@ int i915_gem_context_create_ioctl(struct drm_device *dev, void *data,
        struct intel_context *ctx;
        int ret;
-       if (!contexts_enabled(dev))
-               return -ENODEV;
-       //if (!contexts_enabled(dev))
- ```
    //      return -ENODEV;
  ```
- ```
    if (args->pad != 0)
  ```
-               return -EINVAL;
-       //if (args->pad != 0)
- ```
    //      return -EINVAL;
  
  ret = i915_mutex_lock_interruptible(dev);
  if (ret)  
  ```

After context creation went through and itouch multitouch initialized. 
I am not sure the reason of these checks but simply ignoring at least for now.

After initialization itouch stuck as ME feedback does not go through. This is probably due to my vmapping vs mapping changes. I will generate a branch for this 4.7 share these changes. However I have to do some cleaning before. So hopefully I will push it tomorrow.

**Comment by pl-semiotics** [comment]
Hi Arda,

No problem, I am glad that I could be helpful!

Interestingly, those checks are present on my kernel but don't seem to be causing any problems; I am unsure why.  It looks to me like the check against `contexts_enabled(dev)` has been there for a while, but the one against `args->pad` is new, and it looks to me like `args` is currently being allocated on the stack in `itouch_create_client_context`, however, so it might just be compiler differences in handling undefined behavior.

I re-exported the deferred context intialization as `intel_execlists_context_deferred_alloc` and called it directly from `itouch_create_client_context` (since it seems like allocating on request may still be the correct solution for the main driver), and that error now seems to be gone.  However, I am now getting a warning about "global vma for this object not found" that seems to be coming from the call to `i915_gem_obj_ggtt_offset_view` on `ce->ringbuf->obj`, which is making me think that there is another change in initialization problem between 4.7 and my intel-drm-next tree (lots of churn in DRM lately, unfortunately for us).  This is causing the GuC client creation to fail, which seems to result in a cascade of failed sends to the GuC and then a null pointer dereference in `reacquire_guc_db`.

**Comment by peter-sa** [comment]
Hi Arda,

No problem, I am glad that I could be helpful!

Interestingly, those checks are present on my kernel but don't seem to be causing any problems; I am unsure why.  It looks to me like the check against `contexts_enabled(dev)` has been there for a while, but the one against `args->pad` is new, and it looks to me like `args` is currently being allocated on the stack in `itouch_create_client_context`, however, so it might just be compiler differences in handling undefined behavior.

I re-exported the deferred context intialization as `intel_execlists_context_deferred_alloc` and called it directly from `itouch_create_client_context` (since it seems like allocating on request may still be the correct solution for the main driver), and that error now seems to be gone.  However, I am now getting a warning about "global vma for this object not found" that seems to be coming from the call to `i915_gem_obj_ggtt_offset_view` on `ce->ringbuf->obj`, which is making me think that there is another change in initialization problem between 4.7 and my intel-drm-next tree (lots of churn in DRM lately, unfortunately for us).  This is causing the GuC client creation to fail, which seems to result in a cascade of failed sends to the GuC and then a null pointer dereference in `reacquire_guc_db`.

**Comment by ardacoskunses** [comment]
Oh yes, you should disable reacquire guc dB work queue at least for now as guc allocation has problems. It is a safety check runs every two seconds if doorbell kicked out of cacheline. It is crashing on me too.

**Comment by pl-semiotics** [comment]
I see, that makes sense.  I tried adding a call to `intel_lr_context_pin` to `itouch_create_client_context`, and the rest of the visible GuC client creation problems seem to have gone away.  I am not sure what might have changed recently in order to make this necessary, or whether this is the correct level of call to use, however.

Now the logs don't seem to indicate any problems, but the actual touch input doesn't work, for an unclear reason (do you have any suggestions on how to debug that?)

I believe that I am also seeing wake-after-suspend problems with the patches applied, unfortunately.

**Comment by ardacoskunses** [comment]
That is good news. You can debug this by enabling the following as explained in Wiki:

#define DEBUGITOUCH for Enable General iTouch debug
#define DEBUG_PTOUCH for Enable iTouch ME debug thread
#define DEBUG_THREAD_SLEEP 100 to specify how often the debug thread resumes, smaller number has performance impact but provides more granular data, 3000 would provide balanced information.
#define DUMP_BUF for Dump buffers if debug thread enabled
#define DUMP_BYTES_OF_BUF 128 Specifies how many bytes of buf to Dump

set DEBUG_THREAD_SLEEP 3000, it will dump ME, GUC and intput output buffers status every 3sec.
At the the bottom of the dump you will see GuC Doorbell count. (I am guessing it will stuck at value "0xF" your case same as mine due to buffer mapping changes and ME does not get feedback ) Anyway lets not make speculation :) if you can share data I can tell how to interpret.

**Comment by pl-semiotics** [comment]
I did set those settings earlier, but I wasn't sure how to interpret the data (by the way, do you know of a Precise Touch specification that I can reference?).  I am not sure which number is the doorbell count, as I don't see any 0xF values in there...

How should I share the dmesg output with you? I'd prefer not to share the full logs publically, as I consider some of the information (e.g. memory maps and lists of features/modules) to potentially have some security impact.

**Comment by ardacoskunses** [comment]
There is not public reference. Which was the reason we suffered a lot during implementation.
I do not how to share big files over github but dmesg would help for sure.

Until we find a way, I just need last 10 lines or so of the dump which should come every 3 sec in your dmesg

**Comment by pl-semiotics** [comment]
I have the last 10 lines of a few of the dumps here:

```
[17994.291866] >> == output(ffffc90003f25000)[15][13] ==
[17994.291867] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[17994.291869] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[17994.291871] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[17994.291873] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[17994.291874] >> == DB s:1, c:f ==
[17994.291876] >> == WQ h:240, t:240 ==
[17994.291877] >> == WQ s:1, eng:0 ==
[17994.291879] >> == WQ prio: 1
[17994.291900] [drm:i915_print_itouch_guc_info [i915]] *ERROR* iTouch :ring head = 240
[17994.291915] [drm:i915_print_itouch_guc_info [i915]] *ERROR* iTouch :ring tail = 240

[17997.295517] >> == output(ffffc90003f25000)[15][13] ==
[17997.295518] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[17997.295519] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00 00 00
[17997.295520] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[17997.295521] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[17997.295522] >> == DB s:1, c:f ==
[17997.295523] >> == WQ h:240, t:240 ==
[17997.295524] >> == WQ s:1, eng:0 ==
[17997.295525] >> == WQ prio: 1
[17997.295547] [drm:i915_print_itouch_guc_info [i915]] *ERROR* iTouch :ring head = 240
[17997.295559] [drm:i915_print_itouch_guc_info [i915]] *ERROR* iTouch :ring tail = 240

[18000.301522] >> == output(ffffc90003f25000)[15][13] == 
[18000.301527] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[18000.301531] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[18000.301538] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[18000.301560] 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[18000.301565] >> == DB s:1, c:f ==
[18000.301570] >> == WQ h:240, t:240 ==
[18000.301576] >> == WQ s:1, eng:0 ==
[18000.301580] >> == WQ prio: 1
[18000.301643] [drm:i915_print_itouch_guc_info [i915]] *ERROR* iTouch :ring head = 240
[18000.301684] [drm:i915_print_itouch_guc_info [i915]] *ERROR* iTouch :ring tail = 240
```

I do not know how big the log is if it is compressed (I will try xz & lrzip), but if it is small enough, can I send the dmesg as an compressed file to your Intel email address from the git commits?

**Comment by ardacoskunses** [comment]
[18000.301565] >> == DB s:1, c:**f** == This one is GuC doorbell, there are 16(0x**f**) buffers and each rings once and then stopped. This can mean two things, 
first GuC IRQ does not happen, you can see in the patches we add an IRQ which must come when process complete. 
second If IRQ coming then ME feedback did not go through which means buffers might have an issue 

You can send logs to acoskunses@gmail.com

**Comment by pl-semiotics** [comment]
Ah, okay, that makes sense. I just now sent the dmesg.  Unfortunately I do not have that much time today, but I will see if I can figure out which it is and/or fix it today/tomorrow.

**Comment by pl-semiotics** [comment]
I have not had much time today (and will not this evening), unfortunately.  I do see "Got signal with current buffer index" messages in my dmesg, which looks to me like it means that the IRQ is going through, is that correct?  I have no idea how to figure out what the correct way to do the vmapping is, since that seems to be the problem, any tips?

**Comment by jimdigriz** [comment]
FYI https://github.com/jimdigriz/ipts-linux/commit/9a30e6db5c78d8000476dca93e6c7d7f7de53ad4 fixes your args init problem.

**Comment by pl-semiotics** [comment]
@jimdigriz Great, so it is just the unitialized data problem.  Does the ipts-v4.6.x branch there work correctly?  Do you think that any of the other changes there are relevant to the problems that we are having with 4.7 (where it compiles and doesn't error, but doesn't work)?

Also, while skimming through your other commits, I noticed that jimdigriz@b8ca959436fe8e764489036c707a69255e0bfb70 looks to me like it is losing the call to `mei_cldev_driver_unregister`, was that intentional?

Thanks for looking into this with us!

**Comment by jimdigriz** [comment]
The branch, works if you revert https://github.com/jimdigriz/ipts-linux/commit/f05d6c00fc20db89d8032466f7d07415a6aeb470, I am currently trying to pull inside out the state machine to get the HID device registered with vend/prod id's, which means I can start working on the HID hack which causes the SP4 touchpad to 'sulk'.

As for, mei_cldev_driver_unregister(), you cannot unregister something that failed to register ;)

**Comment by pl-semiotics** [comment]
> The branch, works if you revert jimdigriz@f05d6c0, I am currently trying to pull inside out the state machine to get the HID device registered with vend/prod id's, which means I can start working on the HID hack which causes the SP4 touchpad to 'sulk'.

I see that there are some MEI changes in the other commits there, so I will try to build a kernel with our changes from here and those to see if it works with 4.7, or if there is still a separate problem with the vmapping.

> As for, mei_cldev_driver_unregister(), you cannot unregister something that fail

Right, of course, I don't know why I missed that!

**Comment by jimdigriz** [comment]
I just rebased now I got the HID changes limping along, you may want to revert https://github.com/jimdigriz/ipts-linux/commit/153aac9c3621cb4c73769a08ccee75cb089c460c but it Works For Me(tm)

**Comment by pl-semiotics** [comment]
@jimdigriz, your version of Arda's "MEI changes" patch seems to be different from the one here (and makes your "MEI changes no longer needed" patch fail to apply), any suggestions?  It looks like at least part of what you were reverting is now not in the original patch, but I'm not sure about what's left (the new version doesn't remove the `mei_cl_read_start` from `mei_cl_bus_event_work`, but does add it to `mei_cl_bus_rx_event`).

**Comment by jimdigriz** [comment]
When applying patches from different forks of Linux to completely different forks of Linux, patching is not going to be straight forward.

The following will tell you what has happened:

```
git log -p v4.4-rc8..v4.6.4 drivers/misc/mei/bus.c
```

b54260fe250203657e9eac54771005fe99a5463a appeared in v4.6.1.

I have rebased and squashed the MEI changes commit to make it clearer what should remain.  The patch will only apply to v4.6.1 or above.

**Comment by pl-semiotics** [comment]
Right, of course the patches won't apply cleanly.  In this case, the conflict is there because Arda's MEI changes patch is different (partially reverted) from the version of it that you have (e.g. compare https://github.com/ipts-linux-org/ipts-linux/commit/ee52e6cd31f7dd9d30f20caa6ddd502c67210c1c vs https://github.com/jimdigriz/ipts-linux/commit/316aed65586872724d4be05c2063bd7230706b2a).  I don't completely understand why those changes were revertedl, so I wanted to see what you thought the correct revert patch would be given this different version of Arda's patch.

**Comment by jimdigriz** [comment]
Look at what b54260fe250203657e9eac54771005fe99a5463a actually does.  You have to look at whats in the kernel source code already, it is a moving target.

**Comment by pl-semiotics** [comment]
https://github.com/ipts-linux-org/ipts-linux/commit/b54260fe250203657e9eac54771005fe99a5463a looks to me like it just adds more mutex locks ("mei: bus: call mei_cl_read_start under device lock").  I have already added the lock call to `mei_cl_bus_rx_event`. I was just trying to make sure that I reverted the correct things, since I don't understand what Arda's patch, or what your patch, was trying to do.

**Comment by jimdigriz** [comment]
Its exactly what the MEI changes patch did for that section, though it was a little naughty and moved the read into the hotpath; which also probably increases work as events are not coalesced.

**Comment by pl-semiotics** [comment]
Okay, that makes more sense. I finally got a kernel built that has my version of forward-porting Arda's changes and your other patches on top.  The doorbell count is still stuck at 0xf (after the first two outputs), and there are now some errors that appear to be related to OpenCL:

```
[  146.316689] itouch: f(send_touches_to_os): The OCL OuptutBuffer Header returned as OUTPUT_BUFFER_PAYLOAD_ERROR (Hdr.payloadtype=0x0)
[  146.316694] itouch: f(send_touches_to_os): Error Severity: 1, Error Source: 1, Error String=Fatal Error
[  146.316700] itouch: f(send_touches_to_os): Error code Bytes are[0-3]: 250 : 255 255 : 255
[  146.316704] itouch: f(send_touches_to_os): OCL Kernel Encountered ERROR_SEVERITY_FATAL
[  146.316709] itouch: f(CompleteTouchProcessing): send_touches_to_os returned error status = [0x8000300b]
```

Arda, is this also something else that might be related to the vmapping problem?

**Comment by pl-semiotics** [comment]
@jimdigriz, by the way, are you also planning on trying to update everything to 4.7+? On a Surface Book, Skylake graphics support is a bit too flaky for me on 4.6.x...

Also, since I'm still relatively new to this, how would you suggest (generally) rebasing your branch on a more current tree? So for, I've been just using git rebase, fixing all of the git-detected conflicts with a best guess, building, fixing those conflicts, finding bugs caused by conflicts, fixing those, etc.  Do you know of a better way?

Thanks for all the help!

**Comment by jimdigriz** [comment]
I am not planning to do the 4.7 port, as I am not exactly sure what I could add compared to a 100k employee company with $50bn in annual revenue working on their own hardware and software :)  Besides, I do not benefit from doing the port, though "coreMem is an international consultancy" so I can be persuaded.

The Skylake support was meant to be better in 4.3, then again in 4.4 and 4.5...it seems to be pretty unloved and still is rather awful.

I recommend to you to not focus on "needs latest and shiniest kernel", this driver has a lot of low hanging fruit problems that need fixing.  Suspend does not work reliably, the touchpad (HID changes) goes into a strange latching behaviour (two touch for single touch, three touch for two touch, etc) after a while, for me the touchscreen driver stops working suddenly anywhere between seconds of use and an hour.

Making the driver reliable to me is way more important (and having the driver track a mainline kernel), kernel porting is easy (though tedious, especially for 4.7 as you need to know how the GuC works), but if I am working on making the Surface better, I want to focus on Connected Standby as a five hour battery life is a joke.

**Comment by pl-semiotics** [comment]
> I am not planning to do the 4.7 port, as I am not exactly sure what I could add compared to a 100k employee company with $50bn in annual revenue working on their own hardware and software :) Besides, I do not benefit from doing the port, though "coreMem is an international consultancy" so I can be persuaded.

Any help here would definitely be appreciated: I am not affiliated with Intel (only an amateur kernel developer), and Arda was, but Intel is no longer supporting the IPTS-linux effort.

> The Skylake support was meant to be better in 4.3, then again in 4.4 and 4.5...it seems to be pretty unloved and still is rather awful.

Yeah, it is still rather bad, but especially with powersaving it is way better on the 4.7 drm-intel-next tree than even on 4.6.

> I recommend to you to not focus on "needs latest and shiniest kernel", this driver has a lot of low hanging fruit problems that need fixing. Suspend does not work reliably, the touchpad (HID changes) goes into a strange latching behaviour (two touch for single touch, three touch for two touch, etc) after a while, for me the touchscreen driver stops working suddenly anywhere between seconds of use and an hour.

Makes sense, I will also work on fixing bugs as well as trying to port.

> Making the driver reliable to me is way more important (and having the driver track a mainline kernel), kernel porting is easy (though tedious, especially for 4.7 as you need to know how the GuC works), but if I am working on making the Surface better, I want to focus on Connected Standby as a five hour battery life is a joke.

Yeah, not understanding the GuC well enough is probably my problem here.  I have been doing some work on the Surface battery life myself, especially given Mathew Garrett's points about the lack of deep C-states potentially causing hardware reliability problems on Skylake mobile SKUs.  I have found that if a few of the experimental i915 power saving options are turned on, and all usb devices are set to autosuspend, it is possible to get into C8-10 during normal use (eDP PSR & FBC have to be on), and during sleep that translates to Connected Standby basically actually being used.

I am using these kernel parameters on the Surface Book, along with a Systemd service that runs `powertop --auto-tune` on boot:

```
i915.enable_psr=1 i915.enable_fbc=1 pcie_aspm=force intel_idle.max_cstate=10
```

Unfortunately, my experience has been that FBC and especially PSR are very unstable (screen flashes, X crashes) especially on older kernels.  I will try 4.6 again and see if using 4.6 + new userspace is any better (and if it is, I'll try looking into the other things that you mentioned).  Do you have somewhere else that we could discuss other Surface/Skylake improvements, so that we don't clutter up this thread?

**Comment by pl-semiotics** [comment]
Unfortunately, I am out of time for working on this for (probaby) most of today/tomorrow.  @jimdigriz's 4.6 version doesn't seem to quite work for me, and I haven't had time to figure out why; if anyone is curious, I've attached the logs: 
[dmesg-9.txt](https://github.com/ipts-linux-org/ipts-linux/files/407604/dmesg-9.txt)

**Comment by jimdigriz** [comment]
Did you do the /etc/modprobe.d/i915.conf bit from https://github.com/jimdigriz/ipts-linux/blob/ipts-v4.6.x/README-IPTS.md

**Comment by pl-semiotics** [comment]
I did add that file, although I had to change enable_guc_submission=Y to enable_guc_submission=1 in order for the i915 module to actually load.  It looks like it is working, since the log file includes this line:

```
[    2.731323] Setting dangerous option enable_guc_submission - tainting kernel
```

**Comment by ardacoskunses** [comment]
Alex, come on! 
Porting this octopus driver, which touches dark parts of SoC, firmware and driver, from kernel to kernel is nothing but fun. I dont think anyone gets benefit from it :) 
I am no longer with Intel, this is only hobby now, which only happened by getting inspired by you :)
Anyway, I am now working on Vulkan and trying to keep a relatively stable GFX driver and touch together on SP4.

Regarding to suspend and resume on 4.4 it was very solid based on tests. We could not test power button repetitive press, 
Please file any instability issues here(!), someone will get to it if not me :)

Peter,
I am sorry, so busy these days to spend time on this due to work.

Alex's MEI revert change makes sense, it was a design flow in 4.4 kernel which fixed by our hack, which should not be needed any more. I did not test this on my side but soon I will and update here.

Quick comment:
i915.enable_psr=1 i915.enable_fbc=1 pcie_aspm=force intel_idle.max_cstate=10
These are dangerous settings and I strongly recommend to revert them at least until touch is stable.

**Comment by pl-semiotics** [comment]
Arda,

Thanks for the reply. Now I understand that revert a bit better. Of course it is no problem that you are busy, just too bad about Intel no longer working on Linux support.  Do let me know when you have another chance to work on this, or if there is anything else that I can help with, as I would love to learn more/enough about the driver to really be able to help with this stuff.

Yeah, I know that those options are dangerous (they do mark the kernel as tainted!) and have not been using them with touch.  I have definitely had some problems with them in the past, although not anything that I have been able to fix myself, but they are pretty stable on the 4.7 kernel with the most recent userspace (interestingly, both with and without those, xf86-video-modesetting is more stable than xf86-video-intel...).  I just wanted to mention that I had found that those were able to allow connected standby on the Surface, since the stability problems from them, on recent kernels and without touch, at least, are small enough that I think the tradeoff is worth it in at least some situations.  Mathew Garret is very emphatic that Skylake systems shouldn't be run without deep-C support, also, citing concerns about long-term part reliability from Intel (and I already use my mobile SKU on very compute-heavy workloads, so that's something that I'm rather concerned about), so that + suspend that actually lasts a reasonable amount of time seemed like a good tradeoff to me.

I also have had reasonably good luck with suspend/resume, although I have noticed that, on resume, the machine often suspends again immediately. I haven't localized this to userspace/kernel yet, though, so it could be completely unrelated.  Wifi also has some problems, but I think I have found a patch that fixes them.  I also found a setting (I will try to find it again sometime) that allows the keyboard to wake up the system (I had to use something other than /proc/acpi/wakeup, I think), and that fixed a lot of resume problems for me (and made opening the lid wake the system up).

Alex, Arda,

I have not done that much kernel stuff but I've been trying to learn, mostly by fixing problems  on Surfaces in my spare time (I did a bunch of digging and got half of the SP3 button driver written, for example, but then someone else got the final mainline version done).  I would definitely enjoy continuing to work on various problems plaguing recent surfaces (SB dGPU, intel touch, unstable graphics, ACPI problems, etc.)  I have mostly been doing ACPI so far (BTW it looks like the dGPU interface is roughly similar to the one that is used in most Optimus laptops, so far as to actually have the same GUIID for the _DSM), but something is different about the way to turn it off, that I haven't figured out yet).  Please let me know if you come up with anything in particular that would be good to try to work on!

Thanks again!

**Comment by Aradayn** [comment]
Thank you so much for working on this, @ardacoskunses ! I had almost given up hope that there would be pen and touch support for the SP4 on Linux.

Please let me know if there's anything I can do to help you get this upstream. If you don't have time, I understand. I really appreciate that you got the code out there. I am a dev, though I don't have any kernel or driver experience.

**Comment by jimdigriz** [comment]
> I also have had reasonably good luck with suspend/resume, although I have noticed that, on resume, the machine often suspends again immediately. I haven't localized this to userspace/kernel yet, though, so it could be completely unrelated.

https://github.com/jimdigriz/debian-mssp4/blob/master/root/lib/systemd/system-sleep/cover-wakeup.sh

Documented since April ;)

**Comment by pl-semiotics** [comment]
> I also have had reasonably good luck with suspend/resume, although I have noticed that, on resume, the machine often suspends again immediately. I haven't localized this to userspace/kernel yet, though, so it could be completely unrelated.
> 
> https://github.com/jimdigriz/debian-mssp4/blob/master/root/lib/systemd/system-sleep/cover-wakeup.sh
> 
> Documented since April ;)

Thanks for the link, I will try that out today or tomorrow.  I saw that file before, noticed that I also have the cover set to wake, but somehow missed the "ignore spurious lid events" part.

Regarding IPTS: I have a Surface Book, and previously wasn't able to get any touch with any of the kernels I've tried (including Arda's version here, @jimdigriz's version, and my custom forward-ported version to intel-drm-next a few months ago).  After installing the Windows 10 Anniversary Update, I got new vendor files in Windows (MSHW0079 instead of MSHW0078), and that seems to have made a difference in that touch events now do come through (on all three kernels, although the drm-next port clearly has some major problems).  Unfortunately, in all cases, after some minutes (it seems to be a different interval each time) something appears to go very wrong, and the machine freezes/dies: the display stays up, but the machine is unresponsive to local input or network connections.  I assume that the kernel is somehow dying, but haven't been able to get any kind of trace or core file.

@jimdigriz, on your SP4, did you also have trouble with the older versions of the vendor files? Your machine seems to have been working pre-Anniversary Update, which is when I got the new files (there is also an MSHW0076 for me, but that one doesn't work either).

Any ideas about what might be causing the crashes/how to debug them?

Alex, I just saw your 4.7.5 version; is that in a state where I'd be able to provide any useful information by testing it (plain and with some other options)? I'm hoping that due to the new kernel it will work better with multitouch & with FBC/PSR (which make a really huge difference in power saving due to deep package C-states) (and maybe not have the crashes that I'm seeing with the other versions, which happen even without any tainting options on i915 except for GuC submission).

Thanks again for all the great work!  Let me know if there's anything else that I can do to help with the driver (although, I may not have time to do it for a little while...)

**Comment by jimdigriz** [comment]
The freezes/dies I see, but they are due to the i915 driver being buggy, and I see that even without the IPTS patches.  For crashes, you might get some mileage with:

```
stdbuf -oL dmesg -w | tee logfile
```

I'm running 4.7.4 and there is no reason 4.7.5 would not work so I recommend to just run it.  I am poking a 4.8-rc7 release along, but I need to get some Real Work(tm) done today so that is back on the back burner.

If you want to talk about my fork, it would be best to move the discussion to my Github page/fork, I think this project here is a dead parrot :)

**Comment by ardacoskunses** [comment]
IPTS on kernel 4.9:

https://github.com/ipts-linux-org/ipts-linux-new
